image: ${ARTIFACTORY_SERVER}/dockerhub-remote/python:3


stages:
  - tcat-tests

.helpers: &helpers |
  function validate () {
      "$@"
      if [[ $? -ne 0 ]]; then exit 1; fi
  }

before_script:
  - *helpers


run_taskcat_tests:
  stage: tcat-tests
  image: ${ARTIFACTORY_SERVER}/dockerhub-remote/python:3
  script:
    - pip install taskcat
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - mkdir -p ~/.aws/
    - echo $AWS_CREDENTIALS > ~/.aws/credentials
    - echo $AWS_CONFIG > ~/.aws/config
    - aws s3 ls
  tags:
    - cm-official-docker-executor
