image: ${ARTIFACTORY_SERVER}/dockerhub-remote/python:3


stages:
  - tcat-tests

.helpers: &helpers |
  function validate () {
      "$@"
      if [[ $? -ne 0 ]]; then exit 1; fi
  }

before_script:
  - *helpers


run_taskcat_tests:
  stage: tcat-tests
  image: ${ARTIFACTORY_SERVER}/dockerhub-remote/python:3
  script:
    - pip install taskcat
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    - taskcat test run -o taskcat_outputs/ -i ci/taskcat.yml
  tags:
    - cm-official-docker-executor
