AWSTemplateFormatVersion: 2010-09-09
Description: This template represents an example of parent template to demonstrate how to link Dag/Ingress template
Resources:
  Access:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://cdn.f5.com/product/cloudsolutions/f5-aws-cloudformation-v2/master/examples/modules/dag/dag.yaml
      Parameters:
        numberPublicExternalIPAddresses: 4
        numberPublicMgmtIPAddresses: 1
        provisionExternalBigipLoadBalancer: 'Yes'
        provisionInternalBigipLoadBalancer: 'Yes'
        createAppSecurityGroup: 'Yes'
        provisionPublicIP: 'Yes'
        restrictedSrcAddress: 10.0.0.0/24
        restrictedSrcAddressApp: 10.0.0.0/24
        restrictedSrcPort: 443
        subnetAz1: subnet-0000000000001
        subnetAz2: subnet-0000000000002
        vpc: vpc-0c740ea960d66b7ef
