AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys a full application stack, including a network, bastion host,
  high availability pair of BIGIP VEs and demo applications. It creates a VPC infrastructure for a
  multi-AZ, multi-tier deployment of a Linux based Application infrastructure. It
  will deploy a bastion and managed NAT gateways or NAT instances into the public
  subnet for each Availability Zone. Finally, it will create an optional webapp template
  for demonstration purposes.  **WARNING** This template creates multiple AWS resources.
  You will be billed for the AWS resources used if you create a stack from this template.(qs-1p2474b65)
Conditions:
  govCloudCondition: !Or [!Equals [!Ref 'AWS::Region', us-gov-west-1], !Equals [!Ref 'AWS::Region', us-gov-east-1]]
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Templates Location
        Parameters:
          - s3BucketName
          - s3KeyPrefix
      - Label:
          default: Network Configuration
        Parameters:
          - subnetMask
          - vpcCidr
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - instanceType
          - numberPublicExternalIPAddresses
          - numNics
          - provisionPublicIP
          - restrictedSrcAddress
          - restrictedSrcAddressApp
          - setAppPublicIP
          - sshKey
          - usePublicMgmtAddress
      - Label:
          default: BIG-IP Configuration
        Parameters:
          - bigipRuntimeInitConfig
          - customImageId
          - imageName
          - licenseType
          - throughput
      - Label:
          default: Application Configuration
        Parameters:
          - appDockerImageName
      - Label:
          default: Resources Tags
        Parameters:
          - application
          - costcenter
          - environment
          - group
          - owner
    ParameterLabels:
      appDockerImageName:
        default: Application docker image name
      application:
        default: Application
      bigipRuntimeInitConfig:
        default: BIGIP Runtime Init config
      costcenter:
        default: Cost Center
      customImageId:
        default: Custom Image Id
      environment:
        default: Environment
      group:
        default: Group
      imageName:
        default: F5 BIG-IP Performance Type (PAYG)
      instanceType:
        default: AWS instance type
      licenseType:
        default: Licence type
      numNics:
        default: Number of interfaces to create
      numberPublicExternalIPAddresses:
        default: Number of external public ip address to create
      owner:
        default: Owner
      provisionPublicIP:
        default: Provision Public IP addresses for the BIG-IP interfaces
      restrictedSrcAddress:
        default: Restricted source address to BIG-IP
      restrictedSrcAddressApp:
        default: Restricted source address to application
      s3BucketName:
        default: S3 bucket where Templates are Located
      s3KeyPrefix:
        default: S3 key prefix
      sshKey:
        default: EC2 KeyPair to enable SSH access to the BIG-IP instance
      subnetMask:
        default: Subnet Mask
      throughput:
        default: BIG-IP VE throughput (PAYG)
      usePublicMgmtAddress:
        default: Set management interface with public address
      vpcCidr:
        default: VPC CIDR
  Version: 1.0.0
Parameters:
  appDockerImageName:
    Default: 'f5devcentral/f5-demo-app:1.0.1'
    Description: Application docker image name
    Type: String
  application:
    Default: f5app
    Description: Name of the Application Tag
    Type: String
  bigipRuntimeInitConfig:
    Default: 'https://f5-cft.s3.amazonaws.com/quickstarts-v2/v0.0.0.1/bigip-configurations/runtime-init-conf-2nic-payg.yaml'
    Description: URL for BIGIP Runtime Init config
    Type: String
  costcenter:
    Default: f5costcenter
    Description: Cost Center Tag.
    Type: String
  customImageId:
    ConstraintDescription: Must be a valid AMI Id
    Default: OPTIONAL
    Description: 'If you would like to deploy using a custom BIG-IP image, provide the AMI Id.  **Note**: Unless specifically required, leave the default of **OPTIONAL**'
    MaxLength: 255
    MinLength: 1
    Type: String
  environment:
    Default: f5env
    Description: Environment Tag.
    Type: String
  group:
    Default: f5group
    Description: Group Tag.
    Type: String
  imageName:
    AllowedValues:
      - Best
      - AdvancedWaf
      - PerAppVeAwaf
    ConstraintDescription: Must be a valid F5 BIG-IP VE image type
    Default: Best
    Description: F5 BIG-IP Performance Type
    Type: String
  instanceType:
    AllowedValues:
      - m3.2xlarge
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - cc2.8xlarge
      - c5n.2xlarge
      - c5n.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type for BIG-IP
    Default: m5.2xlarge
    Description: AWS instance type
    Type: String
  licenseType:
    AllowedValues:
      - payg
      - byol
      - bigiq
    Default: payg
    Description: Specifies licence type used for BIGIP VE
    Type: String
  numNics:
    Default: 2
    Description: Number of interfaces to create on BIG-IP instance. Maximum of 3 allowed. Minimum of 1 allowed.
    MaxValue: 3
    MinValue: 1
    Type: Number
  numberPublicExternalIPAddresses:
    Default: 1
    Description: Number of external public ip address to create and associate to external interface. Maximum of 4 allowed. Minimum of 0 allowed.
    MaxValue: 4
    MinValue: 0
    Type: Number
  owner:
    Default: f5owner
    Description: Owner Tag
    Type: String
  restrictedSrcAddress:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: ' The IP address range used to SSH and access management GUI on the EC2 instances'
    MaxLength: '18'
    MinLength: '9'
    Type: String
  restrictedSrcAddressApp:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: The IP address range that can be used to access web traffic (80/443) to the EC2 instances.
    MaxLength: '18'
    MinLength: '9'
    Type: String
  s3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: 'S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Default: aws-quickstart
    Description: 'S3 bucket name for the modules. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Type: String
  s3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/_.-]*$'
    ConstraintDescription: 'Use defaults unless customizing templates and assests that require alternate location. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).'
    Default: quickstart-f5-big-ip-virtual-edition-ha/
    Description: 'S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).'
    Type: String
  sshKey:
    Description: EC2 KeyPair to enable SSH access to the BIG-IP instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  subnetMask:
    ConstraintDescription: 'Subnet mask must be in value of 16-28. Total number of subnets created from VPC must be greater than or equal to number of regions multiplied by number of subnets. Example: 4 AZ with 8 subnets requires VPC supernetting support 32 subnets.'
    Default: 24
    Description: 'Mask for subnets. Valid values include 16-28. Note supernetting of VPC occurs based on mask  provided; therefore, number of networks must be >= to the number of subnets created.Mask for subnets. Valid values include 16-28.'
    MaxValue: 28
    MinValue: 16
    Type: Number
  throughput:
    AllowedValues:
      - 25Mbps
      - 200Mbps
      - 1000Mbps
      - 5000Mbps
      - 10000Mbps
    ConstraintDescription: Select the BIG-IP throughput you want to use
    Default: 1000Mbps
    Description: Maximum amount of throughput for BIG-IP VE
    Type: String
  usePublicMgmtAddress:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Value of true sets management interface with public address. In most production environments this would be set to false.
    Type: String
  version:
    AllowedValues:
      - 15-1-2-009
      - 14-1-3-007
    Default: 15-1-2-009
    Description: Select version of BIG-IP you wish to deploy.
    Type: String
  vpcCidr:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${s3BucketName}.${s3Region}.amazonaws.com/${s3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - { s3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref 'availabilityZones'
        KeyPairName: !Ref 'keyPairName'
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref 'privateSubnet1CIDR'
        PrivateSubnet2ACIDR: !Ref 'privateSubnet2CIDR'
        PublicSubnet1CIDR: !Ref 'publicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'publicSubnet2CIDR'
        VPCCIDR: !Ref 'vpcCIDR'
  BastionStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${s3BucketName}.${s3Region}.amazonaws.com/${s3KeyPrefix}submodules/quickstart-aws-vpc/templates/linux-bastion.template
        - { s3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        BastionAMIOS: Ubuntu-Server-16.04-LTS-HVM
        BastionBanner: ''
        BastionInstanceType: t2.micro
        EnableBanner: 'false'
        EnableTCPForwarding: 'true'
        EnableX11Forwarding: 'true'
        KeyPairName: !Ref 'keyPairName'
        NumBastionHosts: '1'
        PublicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        PublicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        QSS3BucketName: !Ref 'qss3BucketName'
        QSS3KeyPrefix: !Sub '${qss3KeyPrefix}submodules/quickstart-linux-bastion/'
        RemoteAccessCIDR: !Ref 'remoteAccessCIDR'
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
  WorkLoadStack:
    DependsOn: BastionStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${s3BucketName}.${s3Region}.amazonaws.com/${s3KeyPrefix}submodules/quickstart-aws-vpc/templates/workload.yaml
        - { s3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        deploymentName: !Ref 'deploymentName'
        deployDemoWebApp: !Ref 'deployDemoWebApp'
        qss3BucketName: !Ref 'qss3BucketName'
        qss3KeyPrefix: !Ref 'qss3KeyPrefix'
        vpc: !GetAtt 'VPCStack.Outputs.VPCID'
        availabilityZones: !Join
          - ','
          - !Ref 'availabilityZones'
        privateSubnet1ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        privateSubnet2ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        publicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        publicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        sshKey: !Ref 'keyPairName'
        restrictedSrcAddress: !Ref 'vpcCIDR'
        applicationRestrictedSrcAddr: !Ref 'applicationRestrictedSrcAddr'
        bigipImage: !Ref 'bigipImage'
        bigipInstanceType: !Ref 'bigipInstanceType'
        bigipManagementGuiPort: !Ref 'bigipManagementGuiPort'
        bigipScalingMinSize: !Ref 'bigipScalingMinSize'
        bigipScalingMaxSize: !Ref 'bigipScalingMaxSize'
        application: !Ref 'application'
        applicationPoolTagKey: !Ref 'applicationPoolTagKey'
        application1PoolTagValue: !Ref 'application1PoolTagValue'
        application2PoolTagValue: !Ref 'application2PoolTagValue'
        notificationEmail: !Ref 'notificationEmail'
        allowUsageAnalytics: !Ref 'allowUsageAnalytics'
  access:
    Description: access nested stack name
    Value: !GetAtt [Access, Outputs.StackName]
  application:
    Description: application nested stack name
    Value: !GetAtt [Application, Outputs.StackName]
  applicationUrl1:
    Condition: appUrl1
    Description: url to public application address
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt [Dag, Outputs.BigipExternalEipAddress01]
  applicationUrl2:
    Condition: appUrl2
    Description: url to public application address
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt [Dag, Outputs.BigipExternalEipAddress02]
  applicationUrl3:
    Condition: appUrl3
    Description: url to public application address
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt [Dag, Outputs.BigipExternalEipAddress03]
  applicationUrl4:
    Condition: appUrl4
    Description: url to public application address
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt [Dag, Outputs.BigipExternalEipAddress04]
  bigipStandalone:
    Description: bigip-standalone nested stack name
    Value: !GetAtt [BigipStandalone, Outputs.StackName]
  dag:
    Description: dag nested stack name
    Value: !GetAtt [Dag, Outputs.StackName]
  managementUrl443:
    Condition: mgmtUrl443
    Description: url to public management address
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt [Dag, Outputs.BigipManagementEipAddress01]
  managementUrl8443:
    Condition: mgmtUrl8443
    Description: url to public management address
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt [Dag, Outputs.BigipManagementEipAddress01]
        - ':8443'
  network:
    Description: network nested stack name
    Value: !GetAtt [Network, Outputs.StackName]
