AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys a full application stack, including a network, bastion host,
  high availability pair of BIG-IP VEs and demo applications. It creates a VPC infrastructure for a
  multi-AZ, multi-tier deployment of a Linux based Application infrastructure. It
  will deploy a bastion and managed NAT gateways or NAT instances into the public
  subnet for each Availability Zone. Finally, it will create an optional webapp template
  for demonstration purposes.  **WARNING** This template creates multiple AWS resources.
  You will be billed for the AWS resources used if you create a stack from this template.(qs-1p2474b65)
Conditions:
  provisionBastion: !Equals
    - 'No'
    - !Ref provisionPublicIpMgmt
  govCloudCondition: !Or [!Equals [!Ref 'AWS::Region', us-gov-west-1], !Equals [!Ref 'AWS::Region', us-gov-east-1]]
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Templates Location
        Parameters:
          - qss3BucketName
          - qss3KeyPrefix
      - Label:
          default: Network Configuration
        Parameters:
          - provisionPublicIpMgmt
          - provisionPublicIpVip
          - availabilityZones
          - privateSubnet1ACIDR
          - privateSubnet1ASelfAddress
          - privateSubnet1BCIDR
          - privateSubnet2ACIDR
          - privateSubnet2ASelfAddress
          - privateSubnet2BCIDR
          - publicSubnet1CIDR
          - publicSubnet1SelfAddress
          - publicSubnet1VipAddress
          - publicSubnet2CIDR
          - publicSubnet2SelfAddress
          - publicSubnet2VipAddress
          - vpcCIDR
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - keyPairName
          - remoteAccessCIDR
          - restrictedSrcAddress
          - restrictedSrcAddressApp
      - Label:
          default: BIG-IP Configuration
        Parameters:
          - bigipInstanceType
          - bigipRuntimeInitConfig01
          - bigipRuntimeInitConfig02
          - cfeS3Bucket
          - customImageId
      - Label:
          default: Resources Tags
        Parameters:
          - application
          - costCenter
          - environment
          - group
          - owner
    ParameterLabels:
      application:
        default: Application
      availabilityZones:
        default: Availability Zones
      bigipImageName:
        default: BIG-IP performance type
      bigipInstanceType:
        default: AWS instance type
      bigipRuntimeInitConfig01:
        default: BIG-IP Runtime Init config for first BIG-IP instance
      bigipRuntimeInitConfig02:
        default: BIG-IP Runtime Init config for second BIG-IP instance
      cfeS3Bucket:
        default: S3 bucket used as BIG-IP storage for failover solution
      costCenter:
        default: Cost Center
      customImageId:
        default: Custom Image Id
      environment:
        default: Environment
      group:
        default: Group
      keyPairName:
        default: EC2 KeyPair to enable SSH access to EC2 instances
      owner:
        default: Owner
      privateSubnet1ACIDR:
        default: CIDR block for private subnet 1 in AZ1
      privateSubnet1ASelfAddress:
        default: Static self IP address for private subnet 1 in AZ1.
      privateSubnet1BCIDR:
        default: CIDR block for private subnet 1 in AZ2
      privateSubnet2ACIDR:
        default: CIDR block for private subnet 2 in AZ1
      privateSubnet2ASelfAddress:
        default: Static self IP address for private subnet 2 in AZ1.
      privateSubnet2BCIDR:
        default: CIDR block for private subnet 2 in AZ2
      provisionPublicIpMgmt:
        default: Provision public IP addresses for the BIG-IP management network interfaces.
      provisionPublicIpVip:
        default: Provision public IP addresses for the BIG-IP external network interfaces.
      publicSubnet1CIDR:
        default: CIDR block for public subnet 1 in AZ1
      publicSubnet1SelfAddress:
        default: Static self IP address for public subnet 1 in AZ1.
      publicSubnet1VipAddress:
        default: Static VIP IP address for public subnet 1 in AZ1.
      publicSubnet2CIDR:
        default: CIDR block for public subnet 2 in AZ2
      publicSubnet2SelfAddress:
        default: Static self IP address for public subnet 2 in AZ1.
      publicSubnet2VipAddress:
        default: Static VIP IP address for public subnet 2 in AZ1.
      qss3BucketName:
        default: S3 bucket where templates are located
      qss3KeyPrefix:
        default: S3 key prefix
      remoteAccessCIDR:
        default: Restricted source address to bastion
      restrictedSrcAddress:
        default: Restricted source address to BIG-IP
      restrictedSrcAddressApp:
        default: Restricted source address to application
      vpcCIDR:
        default: VPC CIDR
  Version: 1.0.0
Parameters:
  application:
    Default: f5app
    Description: Name of the Application Tag
    Type: String
  availabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note: The logical order is preserved and only 2 AZs are used for this deployment.'
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  bigipImageName:
    AllowedValues:
      - Best
      - AdvancedWaf
      - PerAppVeAwaf
    ConstraintDescription: Must be a valid F5 BIG-IP VE image type
    Default: Best
    Description: F5 BIG-IP Performance Type
    Type: String
  bigipInstanceType:
    AllowedValues:
      - m3.2xlarge
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - cc2.8xlarge
      - c5n.2xlarge
      - c5n.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type for BIG-IP
    Default: m5.2xlarge
    Description: AWS instance type
    Type: String
  bigipRuntimeInitConfig01:
    Description: URL for BIG-IP Runtime Init config
    Type: String
  bigipRuntimeInitConfig02:
    Description: URL for BIG-IP Runtime Init config
    Type: String
  cfeS3Bucket:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: 'S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Default: aws-quickstart-cfe
    Description: S3 bucket used as BIG-IP storage for Failover solution
    Type: String
  costCenter:
    Default: f5costcenter
    Description: Cost Center Tag.
    Type: String
  customImageId:
    ConstraintDescription: Must be a valid AMI Id
    Default: OPTIONAL
    Description: 'If you would like to deploy using a custom BIG-IP image, provide the AMI Id.  **Note**: Unless specifically required, leave the default of **OPTIONAL**'
    MaxLength: 255
    MinLength: 1
    Type: String
  environment:
    Default: f5env
    Description: Environment Tag.
    Type: String
  group:
    Default: f5group
    Description: Group Tag.
    Type: String
  keyPairName:
    Description: EC2 KeyPair to enable SSH access to EC2 instances which include BIG-IP, Bastion, and demo application instances.
    Type: 'AWS::EC2::KeyPair::KeyName'
  owner:
    Default: f5owner
    Description: Owner Tag
    Type: String
  privateSubnet1ACIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.11.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  privateSubnet1ASelfAddress: 
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: IP address parameter must be in the form x.x.x.x and a member of the privateSubnet1ACIDR block
    Default: 10.0.11.180
    Description: Required. Type the static self IP address here.
    Type: String
  privateSubnet1BCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.12.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  privateSubnet2ACIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.21.0/24
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  privateSubnet2ASelfAddress:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: IP address parameter must be in the form x.x.x.x and a member of the privateSubnet2ACIDR block
    Default: 10.0.21.218
    Description: Required. Type the static self IP address here.
    Type: String
  privateSubnet2BCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.22.0/24
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  provisionPublicIpMgmt:
    AllowedValues:
      - 'No'
      - 'Yes'
    Default: 'No'
    Description: Choose True to provision public IP addresses for the BIG-IP management network interfaces. By default, no public IP addresses are provisioned.
    Type: String
  provisionPublicIpVip:
    AllowedValues:
      - 'No'
      - 'Yes'
    Default: 'No'
    Description: Choose True to provision public IP addresses for the BIG-IP external network interfaces. By default, no public IP addresses are provisioned.
    Type: String
  publicSubnet1CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.10.0/24
    Description: CIDR block for the public DMZ subnet 1 located in Availability Zone 1.
    Type: String
  publicSubnet1SelfAddress:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: IP address parameter must be in the form x.x.x.x and a member of the publicSubnet1CIDR block
    Default: 10.0.10.89
    Description: Required. Type the static external self IP address here.
    Type: String
  publicSubnet1VipAddress:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: IP address parameter must be in the form x.x.x.x and a member of the publicSubnet1CIDR block
    Default: 10.0.10.90
    Description: Required. Type the static external service IP address here.
    Type: String
  publicSubnet2CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.20.0/24
    Description: CIDR block for the public DMZ subnet 2 located in Availability Zone 2.
    Type: String
  publicSubnet2SelfAddress:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: IP address parameter must be in the form x.x.x.x and a member of the publicSubnet2CIDR block
    Default: 10.0.20.158
    Description: Required. Type the static external self IP address here.
    Type: String
  publicSubnet2VipAddress:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: IP address parameter must be in the form x.x.x.x and a member of the publicSubnet2CIDR block
    Default: 10.0.20.157
    Description: Required. Type the static external service IP address here.
    Type: String
  qss3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: 'S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Default: aws-quickstart
    Description: 'S3 bucket name for the modules. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Type: String
  qss3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/_.-]*$'
    ConstraintDescription: 'Use defaults unless customizing templates and assests that require alternate location. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).'
    Default: quickstart-f5-big-ip-virtual-edition-ha/
    Description: 'S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).'
    Type: String
  remoteAccessCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions.
    Type: String
  restrictedSrcAddress:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: ' The IP address range used to SSH and access management GUI on the EC2 instances'
    MaxLength: '18'
    MinLength: '9'
    Type: String
  restrictedSrcAddressApp:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: The IP address range that can be used to access web traffic (80/443) to the EC2 instances.
    MaxLength: '18'
    MinLength: '9'
    Type: String
  vpcCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
Resources:
  BastionStack:
    Condition: provisionBastion
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${qss3BucketName}.${qss3Region}.amazonaws.com/${qss3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template
        - { qss3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        BastionAMIOS: Ubuntu-Server-20.04-LTS-HVM
        BastionBanner: ''
        BastionInstanceType: t2.micro
        EnableBanner: 'false'
        EnableTCPForwarding: 'true'
        EnableX11Forwarding: 'true'
        KeyPairName: !Ref 'keyPairName'
        NumBastionHosts: '1'
        PublicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        PublicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        QSS3BucketName: !Ref 'qss3BucketName'
        QSS3KeyPrefix: !Sub '${qss3KeyPrefix}submodules/quickstart-linux-bastion/'
        RemoteAccessCIDR: !Ref 'remoteAccessCIDR'
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
  WorkLoadStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${qss3BucketName}.${qss3Region}.amazonaws.com/${qss3KeyPrefix}templates/workload.yaml
        - { qss3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        application: !Ref application
        bigipRuntimeInitConfig01: !Ref bigipRuntimeInitConfig01
        bigipRuntimeInitConfig02: !Ref bigipRuntimeInitConfig02
        cfeS3Bucket: !Ref cfeS3Bucket
        costcenter: !Ref costCenter 
        customImageId: !Ref customImageId
        environment: !Ref environment
        group: !Ref group
        imageName: !Ref bigipImageName
        instanceType: !Ref bigipInstanceType
        owner: !Ref owner
        privateSubnet1ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        privateSubnet1SelfAddress: !Ref privateSubnet1ASelfAddress
        privateSubnet2ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        privateSubnet2SelfAddress: !Ref privateSubnet2ASelfAddress
        provisionPublicIpMgmt: !Ref provisionPublicIpMgmt
        provisionPublicIpVip: !Ref provisionPublicIpVip
        publicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        publicSubnet1SelfAddress: !Ref publicSubnet1SelfAddress
        publicSubnet1VipAddress: !Ref publicSubnet1VipAddress
        publicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        publicSubnet2SelfAddress: !Ref publicSubnet2SelfAddress
        publicSubnet2VipAddress: !Ref publicSubnet2VipAddress
        restrictedSrcAddress: !Ref restrictedSrcAddress
        restrictedSrcAddressApp: !Ref restrictedSrcAddressApp
        s3BucketName: !Ref qss3BucketName
        s3KeyPrefix: !Ref qss3KeyPrefix
        sshKey: !Ref keyPairName
        vpc: !GetAtt 'VPCStack.Outputs.VPCID'
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${qss3BucketName}.${qss3Region}.amazonaws.com/${qss3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - { qss3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref 'availabilityZones'
        CreateAdditionalPrivateSubnets: 'true'
        KeyPairName: !Ref 'keyPairName'
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref 'privateSubnet1ACIDR'
        PrivateSubnet1BCIDR: !Ref 'privateSubnet1BCIDR'
        PrivateSubnet2ACIDR: !Ref 'privateSubnet2ACIDR'
        PrivateSubnet2BCIDR: !Ref 'privateSubnet2BCIDR'
        PublicSubnet1CIDR: !Ref 'publicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'publicSubnet2CIDR'
        VPCCIDR: !Ref 'vpcCIDR'
Outputs:
  access:
    Description: access nested stack name
    Value: !GetAtt [WorkLoadStack, Outputs.access]
  bastionHost:
    Condition: provisionBastion
    Description: bastion host public ip
    Value: !GetAtt [BastionStack, Outputs.EIP1] 
  bigipInstance01:
    Description: bigip instance 1 nested stack name
    Value: !GetAtt [WorkLoadStack, Outputs.bigipInstance01]
  bigipInstance02:
    Description: bigip instance 2 nested stack name
    Value: !GetAtt [WorkLoadStack, Outputs.bigipInstance02]
  cfeS3Bucket:
    Description: cfe s3 bucket created and used for cloud-failover-extension
    Value: !Ref cfeS3Bucket 
  dag:
    Description: dag nested stack name
    Value: !GetAtt [WorkLoadStack, Outputs.dag]
  workLoadStack:
    Description: workload nested stack name
    Value: !GetAtt [WorkLoadStack, Outputs.stackName]