AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys a full application stack, including a network, bastion host,
  high availability pair of BIGIP VEs and demo applications. It creates a VPC infrastructure for a
  multi-AZ, multi-tier deployment of a Linux based Application infrastructure. It
  will deploy a bastion and managed NAT gateways or NAT instances into the public
  subnet for each Availability Zone. Finally, it will create an optional webapp template
  for demonstration purposes.  **WARNING** This template creates multiple AWS resources.
  You will be billed for the AWS resources used if you create a stack from this template.(qs-1p2474b65)
Conditions:
  isPaygLicensing: !Equals
    - payg
    - !Ref licenseType
  noCustomImageId: !Equals
    - OPTIONAL
    - !Ref customImageId
  govCloudCondition: !Or [!Equals [!Ref 'AWS::Region', us-gov-west-1], !Equals [!Ref 'AWS::Region', us-gov-east-1]]
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Templates Location
        Parameters:
          - qss3BucketName
          - qss3KeyPrefix
      - Label:
          default: Network Configuration
        Parameters:
          - availabilityZones
          - vpcCIDR
          - publicSubnet1CIDR
          - publicSubnet2CIDR
          - privateSubnet1CIDR
          - privateSubnet2CIDR
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - remoteAccessCIDR
          - keyPairName
      - Label:
          default: BIG-IP Configuration
        Parameters:
          - bigipRuntimeInitConfig
          - customImageId
          - bigipInstanceType
          - bigipImage
          - licenseType
          - throughput
      - Label:
          default: Application Configuration
        Parameters:
          - appDockerImageName
      - Label:
          default: Resources Tags
        Parameters:
          - application
          - costcenter
          - environment
          - group
          - owner
    ParameterLabels:
      appDockerImageName:
        default: Application docker image name
      application:
        default: Application
      bigipRuntimeInitConfig:
        default: BIGIP Runtime Init config
      costcenter:
        default: Cost Center
      customImageId:
        default: Custom Image Id
      environment:
        default: Environment
      group:
        default: Group
      imageName:
        default: F5 BIG-IP Performance Type (PAYG)
      bigipInstanceType:
        default: AWS instance type
      licenseType:
        default: Licence type
      owner:
        default: Owner
      restrictedSrcAddress:
        default: Restricted source address to BIG-IP
      restrictedSrcAddressApp:
        default: Restricted source address to application
      qss3BucketName:
        default: S3 bucket where Templates are Located
      qss3KeyPrefix:
        default: S3 key prefix
      keyPairName:
        default: EC2 KeyPair to enable SSH access to the BIG-IP instance
      throughput:
        default: BIG-IP VE throughput (PAYG)
      availabilityZones:
        default: Availability Zones
      remoteAccessCIDR:
        default: Allowed Bastion External Access CIDR
      vpcCIDR:
        default: VPC CIDR
  Version: 1.0.0
Parameters:
  appDockerImageName:
    Default: 'f5devcentral/f5-demo-app:1.0.1'
    Description: Application docker image name
    Type: String
  application:
    Default: f5app
    Description: Name of the Application Tag
    Type: String
  availabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note:
      The logical order is preserved and only 2 AZs are used for this deployment.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  bigipImage:
    Description: BIG-IP Image for BIG-IP VE.
    Type: String
    Default: PerAppVeLtm25Mbps
    AllowedValues:
      - Good25Mbps
      - Good200Mbps
      - Good1000Mbps
      - Good5000Mbps
      - Better25Mbps
      - Better200Mbps
      - Better1000Mbps
      - Better5000Mbps
      - Best25Mbps
      - Best200Mbps
      - Best1000Mbps
      - Best5000Mbps
      - PerAppVeLtm25Mbps
      - PerAppVeLtm200Mbps
    ConstraintDescription: Select the BIG-IP Image you want to use
  bigipRuntimeInitConfig:
    Default: 'https://f5-cft.s3.amazonaws.com/quickstarts-v2/v0.0.0.1/bigip-configurations/runtime-init-conf-2nic-payg.yaml'
    Description: URL for BIGIP Runtime Init config
    Type: String
  costcenter:
    Default: f5costcenter
    Description: Cost Center Tag.
    Type: String
  customImageId:
    ConstraintDescription: Must be a valid AMI Id
    Default: OPTIONAL
    Description: 'If you would like to deploy using a custom BIG-IP image, provide the AMI Id.  **Note**: Unless specifically required, leave the default of **OPTIONAL**'
    MaxLength: 255
    MinLength: 1
    Type: String
  environment:
    Default: f5env
    Description: Environment Tag.
    Type: String
  group:
    Default: f5group
    Description: Group Tag.
    Type: String
  bigipImageName:
    AllowedValues:
      - Best
      - AdvancedWaf
      - PerAppVeAwaf
    ConstraintDescription: Must be a valid F5 BIG-IP VE image type
    Default: Best
    Description: F5 BIG-IP Performance Type
    Type: String
  bigipInstanceType:
    AllowedValues:
      - m3.2xlarge
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - cc2.8xlarge
      - c5n.2xlarge
      - c5n.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type for BIG-IP
    Default: m5.2xlarge
    Description: AWS instance type
    Type: String
  licenseType:
    AllowedValues:
      - payg
      - byol
      - bigiq
    Default: payg
    Description: Specifies licence type used for BIGIP VE
    Type: String
  owner:
    Default: f5owner
    Description: Owner Tag
    Type: String
  restrictedSrcAddress:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: ' The IP address range used to SSH and access management GUI on the EC2 instances'
    MaxLength: '18'
    MinLength: '9'
    Type: String
  restrictedSrcAddressApp:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: The IP address range that can be used to access web traffic (80/443) to the EC2 instances.
    MaxLength: '18'
    MinLength: '9'
    Type: String
  qss3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: 'S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Default: aws-quickstart
    Description: 'S3 bucket name for the modules. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Type: String
  qss3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/_.-]*$'
    ConstraintDescription: 'Use defaults unless customizing templates and assests that require alternate location. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).'
    Default: quickstart-f5-big-ip-virtual-edition-ha/
    Description: 'S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).'
    Type: String
  keyPairName:
    Description: EC2 KeyPair to enable SSH access to the BIG-IP instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  throughput:
    AllowedValues:
      - 25Mbps
      - 200Mbps
      - 1000Mbps
      - 5000Mbps
      - 10000Mbps
    ConstraintDescription: Select the BIG-IP throughput you want to use
    Default: 1000Mbps
    Description: Maximum amount of throughput for BIG-IP VE
    Type: String
  version:
    AllowedValues:
      - 15-1-2-009
      - 14-1-3-007
    Default: 15-1-2-009
    Description: Select version of BIG-IP you wish to deploy.
    Type: String
  notificationEmail:
    Description: Valid email address to send auto-scaling event notifications.
    ConstraintDescription: Must be a valid email address.
    AllowedPattern: .+@.+
    Type: String
  privateSubnet1ACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.11.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  privateSubnet1BCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.12.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  privateSubnet2ACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.21.0/24
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  privateSubnet2BCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.22.0/24
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  publicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.10.0/24
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone
      1.
    Type: String
  publicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.20.0/24
    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone
      2.
    Type: String
  remoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions.
    Type: String
  vpcCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${qss3BucketName}.${qss3Region}.amazonaws.com/${qss3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - { qss3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref 'availabilityZones'
        KeyPairName: !Ref 'keyPairName'
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref 'privateSubnet1ACIDR'
        PrivateSubnet1BCIDR: !Ref 'privateSubnet1BCIDR'
        PrivateSubnet2ACIDR: !Ref 'privateSubnet2ACIDR'
        PrivateSubnet2BCIDR: !Ref 'privateSubnet2BCIDR'
        PublicSubnet1CIDR: !Ref 'publicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'publicSubnet2CIDR'
        VPCCIDR: !Ref 'vpcCIDR'
  BastionStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${qss3BucketName}.${qss3Region}.amazonaws.com/${qss3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template
        - { qss3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        BastionAMIOS: Ubuntu-Server-20.04-LTS-HVM
        BastionBanner: ''
        BastionInstanceType: t2.micro
        EnableBanner: 'false'
        EnableTCPForwarding: 'true'
        EnableX11Forwarding: 'true'
        KeyPairName: !Ref 'keyPairName'
        NumBastionHosts: '1'
        PublicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        PublicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        QSS3BucketName: !Ref 'qss3BucketName'
        QSS3KeyPrefix: !Sub '${qss3KeyPrefix}submodules/quickstart-linux-bastion/'
        RemoteAccessCIDR: !Ref 'remoteAccessCIDR'
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
  WorkLoadStack:
    DependsOn: BastionStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${qss3BucketName}.${qss3Region}.amazonaws.com/${qss3KeyPrefix}templates/workload.yaml
        - { qss3Region: !If [govCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        s3BucketName: !Ref qss3BucketName
        s3KeyPrefix: !Ref qss3KeyPrefix
        vpc: !GetAtt 'VPCStack.Outputs.VPCID'
        privateSubnet1ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        privateSubnet2ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        publicSubnet1ID: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        publicSubnet2ID: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
        sshKey: !Ref keyPairName
        numNics: 2
        bigipRuntimeInitConfig: !Ref bigipRuntimeInitConfig
        customImageId: 'OPTIONAL'
        numberPublicExternalIPAddresses: 1
        restrictedSrcAddress: !Ref restrictedSrcAddress
        restrictedSrcAddressApp: !Ref restrictedSrcAddressApp
        imageName: !Ref bigipImageName
        instanceType: !Ref bigipInstanceType
        application: !Ref application
