AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Access Template is intended to deploy IAM roles for all BIGIP Cloud Solutions
  (i.e. High-Availability or Autoscale)
  Secret Manager service.
Mappings:
  Transformations:
    Boolean:
      'No': 'false'
      'Yes': 'true'
Conditions:
  Failover: !Equals
    - !Ref solutionType
    - failover
  Standard: !Or
    - !Equals
      - !Ref solutionType
      - autoscale
    - !Equals
      - !Ref solutionType
      - standalone
  BigIq: !Equals
    - !Ref createBigIqRoles
    - 'true'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: IAM ROLES
        Parameters:
          - solutionType
          - s3Bucket
          - createBigIqRoles
          - bigIqSecretArn
    ParameterLabels:
      application:
        default: Application
      costcenter:
        default: Cost Center
      environment:
        default: Environment
      group:
        default: Group
      owner:
        default: Owner
      solutionType:
        default: Cloud Solution type
      s3Bucket:
        default: S3 bucket used as BIGIP storage for Failover solution
      createBigIqRoles: 
        default: Creates IAM roles for BIG-IQ
      bigIqSecretArn:
        default: ARN of Secrets Manager secret
  Version: 1.0.0
Outputs:
  StackName:
    Description: access nested stack name
    Value: !Ref "AWS::StackName"
  BigipInstanceProfile:
    Description: BIGIP instance profile with applied IAM policy.
    Value: !If
      - Standard
      - !Ref BigipStandardInstanceProfile
      - !Ref BigipHighAvailabilityInstanceProfile
  LambdaAccessRole:
    Description: IAM policy for BIG-IQ lambda function
    Value: !If
      - BigIq
      - !GetAtt LambdaAccessRole.Arn
      - OPTIONAL 
  CopyZipsRole:
    Description: IAM policy for BIG-IQ lambda function
    Value: !If
      - BigIq
      - !GetAtt CopyZipsRole.Arn
      - OPTIONAL
  BigIqNotificationRole:
    Description: IAM policy for Lifecycle Hook notifications
    Value: !If
      - BigIq
      - !GetAtt BigIqNotificationRole.Arn
      - OPTIONAL  
Parameters:
  solutionType:
    Description: Defines solution type to select provision correct IAM role
    Type: String
    MaxLength: 20
    Default: standalone
    AllowedValues:
      - failover
      - autoscale
      - standalone
  s3Bucket:
    Description: Provides BIG-IP S3 Bucket name
    Type: String
    Default: OPTIONAL
  createBigIqRoles:
    Description: Value of true creates IAM roles required to revoke license assignments from BIG-IQ
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  bigIqSecretArn:
    Description: The ARN of the AWS secret containing the password used during BIG-IP licensing via BIG-IQ
    Type: String
    Default: OPTIONAL
  application:
    Default: f5app
    Description: Name of the Application Tag
    Type: String
  environment:
    Default: f5env
    Description: Name of the Environment Tag
    Type: String
  group:
    Default: f5group
    Description: Name of the Group Tag
    Type: String
  owner:
    Default: f5owner
    Description: Name of the Owner Tag
    Type: String
  costcenter:
    Default: f5costcenter
    Description: Name of the Cost Center Tag
    Type: String
Resources:
  CopyZipsRole:
    Condition: BigIq
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyName: lambda-copier
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:DeleteObject
                Resource: arn:aws:s3:::*
      Tags:
        - Key: Application
          Value: !Ref application
        - Key: Costcenter
          Value: !Ref costcenter
        - Key: Environment
          Value: !Ref environment
        - Key: Group
          Value: !Ref group
        - Key: Owner
          Value: !Ref owner
    Type: 'AWS::IAM::Role'
  LambdaAccessRole:
    Condition: BigIq
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 'ec2:DescribeInstances'
                  - 'autoscaling:CompleteLifecycleAction'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 'secretsmanager:GetSecretValue'
                Effect: Allow
                Resource: !Ref bigIqSecretArn
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Effect: Allow
                Resource: 'arn:aws:logs:*:*:*'
            Version: 2012-10-17
          PolicyName: LambdaAccessPolicy
      Tags:
        - Key: Application
          Value: !Ref application
        - Key: Costcenter
          Value: !Ref costcenter
        - Key: Environment
          Value: !Ref environment
        - Key: Group
          Value: !Ref group
        - Key: Owner
          Value: !Ref owner
    Type: 'AWS::IAM::Role'
  BigIqNotificationRole:
    Condition: BigIq
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: 
              - autoscaling.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole
      Path: /
    Type: AWS::IAM::Role
  BigipStandardAccessRole:
    Condition: Standard
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceStatus'
                  - 'ec2:DescribeAddresses'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeNetworkInterfaceAttribute'
                  - 'ec2:DescribeRouteTables'
                  - 'ec2:DescribeTags'
                  - 'ec2:CreateTags'
                  - 'sts:AssumeRole'
                  - 'cloudformation:ListStackResources'
                  - 'cloudformation:SignalResource'
                  - 'secretsmanager:GetResourcePolicy'
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:PutSecretValue'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:ListSecretVersionIds'
                  - 'secretsmanager:UpdateSecretVersionStage'
                Effect: Allow
                Resource:
                  - '*'
            Version: 2012-10-17
          PolicyName: BigipStandardAcccessPolicy
      Tags:
        - Key: Application
          Value: !Ref application
        - Key: Costcenter
          Value: !Ref costcenter
        - Key: Environment
          Value: !Ref environment
        - Key: Group
          Value: !Ref group
        - Key: Owner
          Value: !Ref owner
    Type: 'AWS::IAM::Role'
  BigipHighAvailabilityAccessRole:
    Condition: Failover
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 's3:ListBucket'
                Effect: Allow
                Resource: !Join
                  - ''
                  - - 'arn:*:s3:::'
                    - !Ref s3Bucket
              - Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                Effect: Allow
                Resource: !Join
                  - ''
                  - - 'arn:*:s3:::'
                    - !Ref s3Bucket
                    - /*
              - Action:
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'autoscaling:SetInstanceProtection'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceStatus'
                  - 'ec2:DescribeAddresses'
                  - 'ec2:AssociateAddress'
                  - 'ec2:DisassociateAddress'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeNetworkInterfaceAttribute'
                  - 'ec2:DescribeRouteTables'
                  - 'ec2:ReplaceRoute'
                  - 'ec2:assignprivateipaddresses'
                  - 'ec2:DescribeTags'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                  - 'sts:AssumeRole'
                  - 'cloudformation:ListStackResources'
                  - 'cloudformation:SignalResource'
                Effect: Allow
                Resource:
                  - '*'
            Version: 2012-10-17
          PolicyName: BigipHighAvailabilityAcccessPolicy
      Tags:
        - Key: Application
          Value: !Ref application
        - Key: Costcenter
          Value: !Ref costcenter
        - Key: Environment
          Value: !Ref environment
        - Key: Group
          Value: !Ref group
        - Key: Owner
          Value: !Ref owner
    Type: 'AWS::IAM::Role'
  BigipStandardInstanceProfile:
    Condition: Standard
    Properties:
      Path: /
      Roles:
        - !Ref BigipStandardAccessRole
    Type: 'AWS::IAM::InstanceProfile'
  BigipHighAvailabilityInstanceProfile:
    Condition: Failover
    Properties:
      Path: /
      Roles:
        - !Ref BigipHighAvailabilityAccessRole
    Type: 'AWS::IAM::InstanceProfile'
